### ISSUE TITLE
Extension not activating

### ISSUE THREAD

**Issue by boschee** [ICTLearningSciences/KNICS_Jupyter_frontend#5]
For some reason, the extension has stopped working on my computer. We (Amandeep and I) tried Chrome and Safari. It just doesn't seem to get activated at all-- nothing is on the console, and the network tab doesn't show any of the notebook events being handled.

I re-cloned the repo and created a fresh conda environment, still no dice. Also tried rebooting computer. Tried both the main branch and the one that worked from 12/16.

Does anyone have ANY idea what could be going on?

**Comment by benjamid** [comment]
It's a bit of a guess in the dark, but maybe the logging endpoint changed? There had been a request for us to make that configurable for where we send messages. If they then changed the endpoint after getting the env feature added, it could be that the endpoint is configurable in this but isn't configured to the right thing. (And the old one wouldn't work because it was baked-in and would also point to the wrong thing). This is just a guess though, as there's no other clear way logging should fail on the older version. Alternate hypothesis is weird firewall or permissions issues.

**Comment by boschee** [comment]
@saggu any thoughts on the logging issue?

**Comment by boschee** [comment]
So, I created an entire new profile on my Mac laptop. Installed zsh and conda and created new ssh keys and everything. Cloned both repos from scratch. The good news is it works. The bad news is it works. ARGH. I guess for the very short term I will just try to get set up with everything I need from scratch on that new profile and work there. 

The only thing that looks odd is that it looks like Jupyter Lab is trying to access some shared resource across users (and failing due to permissions). It's theoretically possible this is related to whatever is blocking me in the other profile.

The file it's trying to access is `/usr/local/share/jupyter/nbconvert/templates/conf.json`, which does not exist, BTW.

```
[E 2023-01-12 09:30:45.625 ServerApp] Uncaught exception GET /api/nbconvert?1673533845111 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/nbconvert?1673533845111', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/jupyter_server/services/nbconvert/handlers.py", line 40, in get
        exporters = await run_sync(base.get_export_names)
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
        return await future
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
        result = context.run(func, *args)
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 147, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 106, in get_exporter
        if getattr(exporter(config=config), "enabled", True):
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 342, in __init__
        super().__init__(config=config, **kw)
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 118, in __init__
        self._init_preprocessors()
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 508, in _init_preprocessors
        conf = self._get_conf()
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 528, in _get_conf
        if conf_path.exists():
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/pathlib.py", line 1407, in exists
        self.stat()
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/pathlib.py", line 1198, in stat
        return self._accessor.stat(self)
    PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/nbconvert/templates/conf.json'
[W 2023-01-12 09:30:45.630 ServerApp] wrote error: 'Unhandled error'
[E 2023-01-12 09:30:45.630 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
    }
[E 2023-01-12 09:30:45.630 ServerApp] 500 GET /api/nbconvert?1673533845111 (e7b984c276c24e52b4a83026c0e9d99e@::1) 465.10ms referer=http://localhost:8888/lab
[E 2023-01-12 09:30:45.631 ServerApp] Uncaught exception GET /api/nbconvert?1673533845107 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/nbconvert?1673533845107', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/jupyter_server/services/nbconvert/handlers.py", line 40, in get
        exporters = await run_sync(base.get_export_names)
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
        return await future
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
        result = context.run(func, *args)
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 147, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 106, in get_exporter
        if getattr(exporter(config=config), "enabled", True):
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 342, in __init__
        super().__init__(config=config, **kw)
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 118, in __init__
        self._init_preprocessors()
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 508, in _init_preprocessors
        conf = self._get_conf()
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 528, in _get_conf
        if conf_path.exists():
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/pathlib.py", line 1407, in exists
        self.stat()
      File "/Users/boscheeclean/opt/anaconda3/envs/knics_jupyter/lib/python3.8/pathlib.py", line 1198, in stat
        return self._accessor.stat(self)
    PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/nbconvert/templates/conf.json'
[W 2023-01-12 09:30:45.631 ServerApp] wrote error: 'Unhandled error'
[E 2023-01-12 09:30:45.631 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
    }
[E 2023-01-12 09:30:45.631 ServerApp] 500 GET /api/nbconvert?1673533845107 (e7b984c276c24e52b4a83026c0e9d99e@::1) 466.49ms referer=http://localhost:8888/lab
[I 2023-01-12 09:30:45.846 LabApp] Build is up to date
[I 2023-01-12 09:31:20.448 ServerApp] Writing notebook-signing key to /Users/boscheeclean/Library/Jupyter/notebook_secret
[W 2023-01-12 09:31:20.484 ServerApp] Notebook january_eval_ta_c_starter.ipynb is not trusted
[I 2023-01-12 09:31:21.024 ServerApp] Kernel started: c828fd0e-d2e8-44bd-bc86-e77b40c9e722
[I 2023-01-12 09:31:22.054 ServerApp] Connecting to kernel c828fd0e-d2e8-44bd-bc86-e77b40c9e722.
[I 2023-01-12 09:31:22.056 ServerApp] Connecting to kernel c828fd0e-d2e8-44bd-bc86-e77b40c9e722.
[I 2023-01-12 09:31:22.075 ServerApp] Connecting to kernel c828fd0e-d2e8-44bd-bc86-e77b40c9e722.
[W 2023-01-12 09:31:22.090 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7fc7b0889c70>
```

**Comment by boschee** [comment]
OK, I went on a witchhunt for everythign jupyter related anywhere in my laptop. Among other things, i did:

```
rm -R ~/.jupyter
rm -R /Users/boschee/Library/Jupyter
rm -R /usr/local/share/jupyter
```

Things now, tentatively, seem to be working on my main profile (clean conda environment of course).

I don't know what got borked, but I seem to have unborked it. Preserving notes here for any future poor souls who encounter this.

**Comment by benjamid** [comment]
@dan100110 Just for situational awareness, Daniel. Hopefully this just won't happen again, but seems like a failure to find a config file?  Is that one we use or just one from Jupyter out of the box which maybe didn't populate?
